### ISSUE TITLE
Add a new TEE type: SE (IBM Secure Execution)

### ISSUE THREAD

**Issue by BbolroC** [virtee/kbs-types#26]
I was wondering if I could raise a PR to add a new TEE type named `Se` like https://github.com/virtee/kbs-types/pull/20, even if the TEE is not specified at https://virtee.io/.

**Comment by larrydewey** [comment]
Yes, please feel free to raise a PR with your desired change, and we will take a look.

**Comment by BbolroC** [comment]
Thanks for the reply. I will raise a PR next week.
